# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import functions_pb2 as functions__pb2


class FederatedAppStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitilizeClients = channel.unary_unary(
                '/FederatedApp/InitilizeClients',
                request_serializer=functions__pb2.Number.SerializeToString,
                response_deserializer=functions__pb2.StatusPair.FromString,
                )
        self.Train = channel.unary_unary(
                '/FederatedApp/Train',
                request_serializer=functions__pb2.TrainTriplet.SerializeToString,
                response_deserializer=functions__pb2.TrainTriplet.FromString,
                )
        self.SendModel = channel.unary_unary(
                '/FederatedApp/SendModel',
                request_serializer=functions__pb2.Model.SerializeToString,
                response_deserializer=functions__pb2.Number.FromString,
                )
        self.FetchClientResults = channel.unary_unary(
                '/FederatedApp/FetchClientResults',
                request_serializer=functions__pb2.Number.SerializeToString,
                response_deserializer=functions__pb2.ResultPair.FromString,
                )


class FederatedAppServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InitilizeClients(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Train(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchClientResults(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FederatedAppServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitilizeClients': grpc.unary_unary_rpc_method_handler(
                    servicer.InitilizeClients,
                    request_deserializer=functions__pb2.Number.FromString,
                    response_serializer=functions__pb2.StatusPair.SerializeToString,
            ),
            'Train': grpc.unary_unary_rpc_method_handler(
                    servicer.Train,
                    request_deserializer=functions__pb2.TrainTriplet.FromString,
                    response_serializer=functions__pb2.TrainTriplet.SerializeToString,
            ),
            'SendModel': grpc.unary_unary_rpc_method_handler(
                    servicer.SendModel,
                    request_deserializer=functions__pb2.Model.FromString,
                    response_serializer=functions__pb2.Number.SerializeToString,
            ),
            'FetchClientResults': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchClientResults,
                    request_deserializer=functions__pb2.Number.FromString,
                    response_serializer=functions__pb2.ResultPair.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FederatedApp', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FederatedApp(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InitilizeClients(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FederatedApp/InitilizeClients',
            functions__pb2.Number.SerializeToString,
            functions__pb2.StatusPair.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Train(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FederatedApp/Train',
            functions__pb2.TrainTriplet.SerializeToString,
            functions__pb2.TrainTriplet.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FederatedApp/SendModel',
            functions__pb2.Model.SerializeToString,
            functions__pb2.Number.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FetchClientResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FederatedApp/FetchClientResults',
            functions__pb2.Number.SerializeToString,
            functions__pb2.ResultPair.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
