# version: '3'
# services:
#   client:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "8080:8080"
#     volumes:
#       - ./:/app

# To build new image toggle commented code

# version: '3'
# services:
#   client:
#     image: adityajnu14/client_arch32 #adityajnu14/client_x86_64
#     ports:
#       - "8080:8080"
#     volumes:
#       - ./:/app


version: "3"
services:
  node01:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8081:8080"
    volumes:
      - ../data/node01:/app/data
      - ../data/node01:/app/Models

  node02:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8082:8080"
    volumes:
      - ../data/node02:/app/data
      - ../data/node02:/app/Models

  node03:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8083:8080"
    volumes:
      - ../data/node03:/app/data
      - ../data/node03:/app/Models

  node04:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8084:8080"
    volumes:
      - ../data/node04:/app/data
      - ../data/node04:/app/Models

  node05:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8085:8080"
    volumes:
      - ../data/node05:/app/data
      - ../data/node05:/app/Models