# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: functions.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x66unctions.proto\"\x16\n\x05Model\x12\r\n\x05model\x18\x01 \x01(\t\"\x17\n\x06Number\x12\r\n\x05value\x18\x01 \x01(\x05\"(\n\nStatusPair\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06status\x18\x02 \x01(\x05\"(\n\nResultPair\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06result\x18\x02 \x01(\t\"7\n\x0cTrainTriplet\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04time\x18\x02 \x01(\x05\x12\r\n\x05model\x18\x03 \x01(\t2\xb1\x01\n\x0c\x46\x65\x64\x65ratedApp\x12*\n\x10InitilizeClients\x12\x07.Number\x1a\x0b.StatusPair\"\x00\x12\'\n\x05Train\x12\r.TrainTriplet\x1a\r.TrainTriplet\"\x00\x12\x1e\n\tSendModel\x12\x06.Model\x1a\x07.Number\"\x00\x12,\n\x12\x46\x65tchClientResults\x12\x07.Number\x1a\x0b.ResultPair\"\x00\x62\x06proto3')



_MODEL = DESCRIPTOR.message_types_by_name['Model']
_NUMBER = DESCRIPTOR.message_types_by_name['Number']
_STATUSPAIR = DESCRIPTOR.message_types_by_name['StatusPair']
_RESULTPAIR = DESCRIPTOR.message_types_by_name['ResultPair']
_TRAINTRIPLET = DESCRIPTOR.message_types_by_name['TrainTriplet']
Model = _reflection.GeneratedProtocolMessageType('Model', (_message.Message,), {
  'DESCRIPTOR' : _MODEL,
  '__module__' : 'functions_pb2'
  # @@protoc_insertion_point(class_scope:Model)
  })
_sym_db.RegisterMessage(Model)

Number = _reflection.GeneratedProtocolMessageType('Number', (_message.Message,), {
  'DESCRIPTOR' : _NUMBER,
  '__module__' : 'functions_pb2'
  # @@protoc_insertion_point(class_scope:Number)
  })
_sym_db.RegisterMessage(Number)

StatusPair = _reflection.GeneratedProtocolMessageType('StatusPair', (_message.Message,), {
  'DESCRIPTOR' : _STATUSPAIR,
  '__module__' : 'functions_pb2'
  # @@protoc_insertion_point(class_scope:StatusPair)
  })
_sym_db.RegisterMessage(StatusPair)

ResultPair = _reflection.GeneratedProtocolMessageType('ResultPair', (_message.Message,), {
  'DESCRIPTOR' : _RESULTPAIR,
  '__module__' : 'functions_pb2'
  # @@protoc_insertion_point(class_scope:ResultPair)
  })
_sym_db.RegisterMessage(ResultPair)

TrainTriplet = _reflection.GeneratedProtocolMessageType('TrainTriplet', (_message.Message,), {
  'DESCRIPTOR' : _TRAINTRIPLET,
  '__module__' : 'functions_pb2'
  # @@protoc_insertion_point(class_scope:TrainTriplet)
  })
_sym_db.RegisterMessage(TrainTriplet)

_FEDERATEDAPP = DESCRIPTOR.services_by_name['FederatedApp']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MODEL._serialized_start=19
  _MODEL._serialized_end=41
  _NUMBER._serialized_start=43
  _NUMBER._serialized_end=66
  _STATUSPAIR._serialized_start=68
  _STATUSPAIR._serialized_end=108
  _RESULTPAIR._serialized_start=110
  _RESULTPAIR._serialized_end=150
  _TRAINTRIPLET._serialized_start=152
  _TRAINTRIPLET._serialized_end=207
  _FEDERATEDAPP._serialized_start=210
  _FEDERATEDAPP._serialized_end=387
# @@protoc_insertion_point(module_scope)
